version: '3'
services:
  java-oauth-server:
    build:
      context: .
    volumes:
      - .:/workspace:cached
      - java-oauth-server:/workspace/java-oauth-server
    working_dir: /workspace
    network_mode: host
    tty: true
volumes:
  java-oauth-server: